name: phone_form_field
description: Flutter phone input integrated with flutter internationalization
version: 7.0.1
homepage: https://github.com/cedvdb/phone_form_field
publish_to: none
environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  circle_flags: ^0.0.3
  # phone_numbers_parser:
  #   git:
  #     url: https://github.com/bitsdominicada/phone_numbers_parser.git
  dart_countries: ^3.0.2
  intl: ^0.17.0
  diacritic: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
